APPROVAL_LABEL_KEY = "approval"
APPROVED_VALUES = {"approved", "true", "yes"}
CONTROLLED_RETRY_ACTION = "controlled_retry"
TUNE_AND_RETRY_ACTION = "tune_and_retry"
RESTART_ACTION = "restart"
MOCK_APPROVER = "mock_oncall_reviewer"
MAX_EXECUTOR_MEMORY_GB = 16
MAX_SHUFFLE_PARTITIONS = 2000
GUARDRAIL_ALLOW = "allow"
GUARDRAIL_REQUIRE_APPROVAL = "require_approval"
GUARDRAIL_BLOCK = "block"

__all__ = [
    "APPROVAL_LABEL_KEY",
    "APPROVED_VALUES",
    "CONTROLLED_RETRY_ACTION",
    "TUNE_AND_RETRY_ACTION",
    "RESTART_ACTION",
    "MOCK_APPROVER",
    "MAX_EXECUTOR_MEMORY_GB",
    "MAX_SHUFFLE_PARTITIONS",
    "GUARDRAIL_ALLOW",
    "GUARDRAIL_REQUIRE_APPROVAL",
    "GUARDRAIL_BLOCK",
]